title: "Retail & Payments"
description: "Medios de pago que sí entiendes."
baseurl: ""
url: "https://retailandpayments.com"

# Configuraciones de motor
markdown: kramdown
highlighter: rouge
incremental: false
exclude: ["README.md", "Gemfile", "Gemfile.lock"]
