title: "Retail & Payments"
description: "Medios de pago que sí entiendes."
baseurl: "/retailandpayments"
url: "https://marcmonf.github.io"

# Esto le dice a GitHub: "No uses temas automáticos, usa mi diseño"
theme: ""

markdown: kramdown
highlighter: rouge
